#include "ergodox.h"
#include "debug.h"
#include "action_layer.h"
#include "../../../../quantum/pincontrol.h"



enum custom_keycodes {
  PLACEHOLDER = SAFE_RANGE, // can always be here
  EPRM,
  VRSN,
  RGB_SLD,

};

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {

  [0] = KEYMAP(
               // left half
               KC_GRAVE,         KC_1,    KC_2,      KC_3,           KC_4,            KC_5,    KC_AUDIO_VOL_DOWN,
               KC_TAB,           KC_Q,    KC_W,      KC_E,           KC_R,            KC_T,    KC_DELETE,
               CTL_T(KC_ESCAPE), KC_A,    KC_S,      KC_D,           KC_F,            KC_G,
               KC_LSPO,          KC_Z,    KC_X,      KC_C,           KC_V,            KC_B,    KC_LBRACKET,
               KC_LCTL,          KC_F13,  KC_INSERT, GUI_T(KC_LEFT), ALT_T(KC_RIGHT),
               // left thumb
               TG(1),KC_HOME,KC_END,
               KC_BSPACE,KC_CAPSLOCK,KC_LBRACKET,
               // right half
               KC_AUDIO_VOL_UP,KC_6,KC_7,KC_8,KC_9,KC_0,KC_MINUS,
               KC_EQUAL,KC_Y,KC_U,KC_I,KC_O,KC_P,KC_BSLASH,
               KC_H,KC_J,KC_K,KC_L,KC_SCOLON,LT(1,KC_QUOTE),
               KC_RBRACKET,KC_N,KC_M,KC_COMMA,KC_DOT,KC_SLASH,
               KC_RSPC,KC_DOWN,KC_UP,KC_CAPSLOCK,KC_CAPSLOCK,MO(1),
               // right thumb
               KC_PGUP,TG(1),KC_PGDOWN,
               KC_EQUAL,KC_ENTER,KC_SPACE
               ),
  // TODO mouse & F-layer
  [1] = KEYMAP(KC_TRANSPARENT,KC_F1,KC_F2,KC_F3,KC_F4,KC_F5,KC_F11,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_MS_UP,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_MS_LEFT,KC_MS_DOWN,KC_MS_RIGHT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,RESET,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_MS_BTN1,KC_MS_BTN2,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_MS_BTN1,KC_MS_BTN2,KC_MS_BTN3,KC_F12,KC_F6,KC_F7,KC_F8,KC_F9,KC_F10,TO(0),KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_UP,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_MS_WH_UP,KC_LEFT,KC_DOWN,KC_RIGHT,KC_TRANSPARENT,KC_MEDIA_PLAY_PAUSE,KC_TRANSPARENT,KC_MS_WH_DOWN,KC_TRANSPARENT,KC_MEDIA_PREV_TRACK,KC_MEDIA_NEXT_TRACK,KC_TRANSPARENT,KC_TRANSPARENT,KC_AUDIO_VOL_UP,KC_AUDIO_VOL_DOWN,KC_AUDIO_MUTE,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_WWW_BACK),

};

const uint16_t PROGMEM fn_actions[] = {
  [1] = ACTION_LAYER_TAP_TOGGLE(1)
};
